<?php

/**
 * @file
 * Provides integration hooks for the GeneHub SOLIDEX module.
 */

declare(strict_types=1);

/**
 * Implements hook_gin_content_form_routes().
 */
function genehub_solidex_gin_content_form_routes(): array {
  return [
    'entity.product_solidex.add_form',
    'entity.product_solidex.edit_form',
    'entity.product_solidex.content_translation_add',
    'entity.product_solidex.content_translation_edit',
  ];
}
